name: multi-platform

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checks repository 
      run: actions/checkout@v4
    - name: prints out OS info
      run: uname -a
    - name: make an empty txt file
      run: touch systeminfo.txt
    - name: write system info to txt file
      run: cat uname -a systeminfo.txt
    
  job_on_windows:
    name: A Window job
    runs-on: windows-latest
    steps:
    - name: Checks repository 
      run: actions/checkout@v4 
    - name: prints out OS info
      run: systeminfo
      
  job_on_macos:
    runs-on: macos-latest
    name: A job on Mac to view system info
    steps:
    - name: Checks repository 
      run: actions/checkout@v4
    - name: prints out OS info
      run: uname -a    
    - name: make an empty txt file
      run: touch systeminfo.txt
    - name: write system info to txt file
      run: cat uname -a systeminfo.txt 
