name: Dependent-jobs

on: 
  push:

jobs:
  Build_job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Simulation of a build command
        run: echo Building application

      - name: Sleep
        run: sleep 5

  Test_job_on_ubuntu:
    runs-on: ubuntu-latest
    needs: Build_job_on_ubuntu
    steps:
      - name: Simulation of a test
        run: echo Testing application

      - name: Maven Java JUnit test all classes
        run: mvn test

  Deploy_job_on_ubuntu:
    runs-on: ubuntu-latest
    needs: Test_job_on_ubuntu
    steps:
      - name: Simulation of application deployment
        run: echo Deploying application

      - name: Maven Java application compile
        run: javac TDDCalculatorTest.java
      - name: Maven Java application compile
        run: javac TestCalculator.java

      - name: Deploying Java file
        run: echo I got no clue how to deploy it
