name: Dependent-jobs

on: 
  push:

jobs:
  Build_job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Simulation of a build command
        run: echo Building application

      - name: Sleep
        run: sleep 5

  Test_job_on_ubuntu:
    runs-on: ubuntu-latest
    needs: Build_job_on_ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Simulation of a test
        run: echo Testing application

      - name: Maven Java JUnit test all classes
        run: mvn clean test

  Deploy_job_on_ubuntu:
    runs-on: ubuntu-latest
    needs: Test_job_on_ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Simulation of application deployment
        run: echo Deploying application

      - name: Compile all Java files
        run: mvn clean package
        
      - name: Deploying Java file
        run: echo I got no clue how to deploy it
