name: multi-platform

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print OS info
      run: uname -a

    - name: Make empty txt file
      run: touch systeminfo.txt

    - name: Write system info to txt file
      run: uname -a >> systeminfo.txt
    - name: print txt file contents
      run: cat systeminfo.txt

  job_on_windows:
    name: A Windows job
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Print OS info
      run: systeminfo
    - name: Make txt file
      shell: cmd
      run: type nul > systeminfo.txt

    - name: Append system info to txt file
      shell: cmd
      run: systeminfo >> systeminfo.txt
    - name: print txt file contents
      shell: cmd
      run: type systeminfo.txt


  job_on_macos:
    name: A job on Mac to view system info
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print OS info
      run: uname -a    

    - name: Make empty txt file
      run: touch systeminfo.txt

    - name: Write system info to txt file
      run: uname -a >> systeminfo.txt
    - name: print txt file contents
      run: cat systeminfo.txt
